// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiCYzQxexRmD7LDLRNY6sBJhtG4oH0fIg',
    appId: '1:1097656554594:web:756aa0e39dbcd557fcad3b',
    messagingSenderId: '1097656554594',
    projectId: 'green-ghana-3ea3b',
    authDomain: 'green-ghana-3ea3b.firebaseapp.com',
    storageBucket: 'green-ghana-3ea3b.appspot.com',
    measurementId: 'G-L85PKR04Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4LBMfQ_TojdUDb4PS2Vvx0ZEPyoPDjIo',
    appId: '1:1097656554594:android:e66c7f017fd79e0dfcad3b',
    messagingSenderId: '1097656554594',
    projectId: 'green-ghana-3ea3b',
    storageBucket: 'green-ghana-3ea3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Wk6VFPac0FQ_TM7OBBXTbQnJ1xcA8hA',
    appId: '1:1097656554594:ios:17d0f5b13a517ec8fcad3b',
    messagingSenderId: '1097656554594',
    projectId: 'green-ghana-3ea3b',
    storageBucket: 'green-ghana-3ea3b.appspot.com',
    androidClientId: '1097656554594-80jauh5tcn8b1t282acgi3squ6kte4h7.apps.googleusercontent.com',
    iosClientId: '1097656554594-uqqikj4o5qstdftca2if2ihi4260ahee.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramAa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Wk6VFPac0FQ_TM7OBBXTbQnJ1xcA8hA',
    appId: '1:1097656554594:ios:17d0f5b13a517ec8fcad3b',
    messagingSenderId: '1097656554594',
    projectId: 'green-ghana-3ea3b',
    storageBucket: 'green-ghana-3ea3b.appspot.com',
    androidClientId: '1097656554594-80jauh5tcn8b1t282acgi3squ6kte4h7.apps.googleusercontent.com',
    iosClientId: '1097656554594-uqqikj4o5qstdftca2if2ihi4260ahee.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramAa',
  );
}
