List<String> images = [
    'https://images.pexels.com/photos/2382665/pexels-photo-2382665.jpeg?auto=compress&cs=tinysrgb&w=800',
    'https://gardentherapy.ca/wp-content/uploads/2018/01/air-plant-watering-2.jpg',
    'https://images.pexels.com/photos/9324330/pexels-photo-9324330.jpeg?auto=compress&cs=tinysrgb&w=800',
    'https://www.happysprout.com/wp-content/uploads/sites/4/2022/01/watering-collard-seedling.jpg?fit=1024%2C682&p=1',
  ];
List<String> titles = ['Site Preparation', 'Seedling Care', 'Digging and Planting', 'Maintenance and Watering'];
List<String> descriptions = [
  'Before planting trees, it is important to get the site ready. This involves cleaning up the area, making sure the soil is healthy and protected, and getting it ready for the new trees. This process includes removing roots and weeds, compacting the soil, and marking where the trees will be planted\n\nWhen choosing the trees to plant, it is important to consider the conditions of the site, such as if the area is dry or wet, and how the tree\'s size and root system will affect nearby structures like buildings and power lines. It is also important to consider what the plants will be used for.\n\nStudies show that plastic can disrupt soil health, reduce plant growth, and slowly move from soils into water bodies. It is therefore important to make sure that plastic wastes are cleared off the site before planting',
  'It is important to take care of the seedlings first, before your due date to plant. To help the seedlings adjust to the new environment, they should be left in the area for at least 24 hours before planting. This will give them time to get used to the conditions and prepare for their new home. When you pick up seedlings from the nursery, it is important to take a few steps to keep them healthy before planting.\n\nKeep the roots moist: This will help prevent the root ball from drying out.\n\nHandle with care: Be gentle when handling the seedlings to avoid crushing them and reducing their chance of survival.\nNote: It\'s also important to water the seedlings lightly, to avoid over-watering and causing waterlogging.',
  'When planting the trees, it is important to follow these steps: \n\n1. Dig the holes: The holes should be twice the width of the root ball and at least 1.5 times as deep as the root ball of the seedling. \n2. Place the seedling in the hole: Take off the polybag or any protective covering and gently place the seedling in the hole, making sure the roots are covered up to the base of the stem. \n3. Handle with care: Be gentle when handling the seedlings to avoid damaging the roots or stem. \n4. Firm the soil: After placing the seedling in the hole, pack the soil around it using your hands, making sure it is secure and stable. \nNote: Don\'t forget to remove any containers that don\'t allow water to flow through before planting.',
  'To help the new trees grow strong and healthy, it\'s important to eliminate weeds that can compete for water and nutrients. Keep a weed-free area around each seedling that\'s at least one meter in diameter, either by using mulch or by hoeing, for the first two years.\n \nMulch (covering the surface of the soil with dead leaves) can help control weeds and reduce water evaporation from the soil. It can be made of wood chips, but only apply it when the soil is moist.\n \nIt\'s also important to make sure the soil stays moist by watering the seedlings at least twice a day, in the morning and evening. This will help keep the soil around the roots hydrated. \nNote: Watering the plants daily is dependent on the type of plant you have.',
];
